name: tiger_fortune_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  path_provider: ^2.1.2
  flutter_countdown_timer: ^4.1.0
  flutter_fortune_wheel: ^1.3.1
  flutter_svg: ^2.0.9
  flutter_slot_machine: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/daily_reward/
    - assets/images/games_elements/
    - assets/images/spot_slot/
    - assets/images/win/
    - assets/images/roulette/
    - assets/images/pokies/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText/SFProText-Bold.ttf
          weight: 700

